export const projects = [
    {
        id: 1,
        title: "KYC Agent",
        description: "Mini Project on Agentic AI at Hebbale Academy.",
        imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
        link: "#",
        tags: ["AI", "Agentic AI", "Python"],
        createdAt: new Date(),
    },
    {
        id: 2,
        title: "E-commerce Sentiment Analysis",
        description: "Built ML model with SVM achieving 85% accuracy on customer review classification.",
        imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800",
        link: "#",
        tags: ["ML", "SVM", "Python"],
        createdAt: new Date(),
    },
    {
        id: 3,
        title: "Radar Alert System",
        description: "Developed Arduino UNO-based radar system for obstacle detection.",
        imageUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&q=80&w=800",
        link: "#",
        tags: ["Arduino", "Hardware", "Sensors"],
        createdAt: new Date(),
    },
    {
        id: 4,
        title: "Custom Text Generation with GPT-2",
        description: "Fine-tuned GPT-2 for domain-specific outputs.",
        imageUrl: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&q=80&w=800",
        link: "#",
        tags: ["NLP", "GPT-2", "Python"],
        createdAt: new Date(),
    },
    {
        id: 5,
        title: "Mental Health Tracking App",
        description: "Developed a Flutter application for mental health tracking.",
        imageUrl: "https://images.unsplash.com/photo-1527335441549-0129bcce37ec?auto=format&fit=crop&q=80&w=800",
        link: "#",
        tags: ["Flutter", "Dart", "Mobile"],
        createdAt: new Date(),
    }
];

export const experience = [
    {
        id: 6,
        role: "Flutter App Development Intern",
        company: "Runshaw Technologies (Remote)",
        duration: "Completed",
        description: "Developed mobile application components using Flutter and Dart. Implemented responsive UI and application logic. Assisted in debugging and improving app performance.",
        order: 1,
    },
    {
        id: 7,
        role: "Hackathon Participant",
        company: "National Level Tech Avishkar 2.0",
        duration: "24-hour challenge",
        description: "Participated in a 24-hour national-level coding challenge.",
        order: 2,
    },
    {
        id: 8,
        role: "Data Science & Analytics Intern",
        company: "HP LIFE",
        duration: "Jan 2025",
        description: "Focused on data analysis and business analytics modules.",
        order: 3,
    },
    {
        id: 9,
        role: "TiEU Semi-Finalist",
        company: "SKINTRUST Startup Idea",
        duration: "Semi-Finals",
        description: "Participated in the semi-finals of TiEU with a startup idea named SKINTRUST.",
        order: 4,
    },
    {
        id: 10,
        role: "Certification: Introduction to Cloud Computing",
        company: "IBM (Coursera)",
        duration: "Completed",
        description: "Foundational knowledge of cloud computing concepts and services.",
        order: 5,
    },
    {
        id: 11,
        role: "Certification: Introduction to Microsoft Azure Cloud Services",
        company: "Microsoft (Coursera)",
        duration: "Completed",
        description: "Introduction to Microsoft Azure Cloud services and core solutions.",
        order: 6,
    },
    {
        id: 12,
        role: "Certification: Connect and Protect: Networks and Network Security",
        company: "Google (Coursera)",
        duration: "Completed",
        description: "Fundamentals of networking and network security practices.",
        order: 7,
    },
    {
        id: 13,
        role: "Certification: Data Science Fundamentals with Python and SQL",
        company: "SkillUp",
        duration: "Completed",
        description: "Foundational data science concepts using Python and SQL for data analysis.",
        order: 8,
    },
    {
        id: 14,
        role: "Certification: Blockchain and Cryptography Overview",
        company: "SkillUp",
        duration: "Completed",
        description: "Overview of blockchain technology and cryptographic principles.",
        order: 9,
    }
];

export const skills = [
    { id: 15, name: "Python", category: "Programming Languages", proficiency: 90 },
    { id: 16, name: "C", category: "Programming Languages", proficiency: 85 },
    { id: 17, name: "Java", category: "Programming Languages", proficiency: 80 },
    { id: 18, name: "HTML/CSS", category: "Programming Languages", proficiency: 85 },
    { id: 19, name: "TensorFlow", category: "AI/ML", proficiency: 85 },
    { id: 20, name: "PyTorch", category: "AI/ML", proficiency: 80 },
    { id: 21, name: "Scikit-learn", category: "AI/ML", proficiency: 90 },
    { id: 22, name: "OpenCV", category: "AI/ML", proficiency: 85 },
    { id: 23, name: "MySQL", category: "Databases", proficiency: 85 },
    { id: 24, name: "MongoDB", category: "Databases", proficiency: 80 },
    { id: 25, name: "Git", category: "Tools", proficiency: 90 },
    { id: 26, name: "Jupyter", category: "Tools", proficiency: 90 },
    { id: 27, name: "VS Code", category: "Tools", proficiency: 95 },
    { id: 28, name: "Google Colab", category: "Tools", proficiency: 90 },
    { id: 29, name: "Communication", category: "Soft Skills", proficiency: 95 },
    { id: 30, name: "Leadership", category: "Soft Skills", proficiency: 90 },
    { id: 31, name: "Problem Solving", category: "Soft Skills", proficiency: 95 },
    { id: 32, name: "Time Management", category: "Soft Skills", proficiency: 90 },
    { id: 33, name: "Adaptability", category: "Soft Skills", proficiency: 90 },
    { id: 34, name: "Attention to detail", category: "Soft Skills", proficiency: 95 },
];

export const education = [
    {
        id: 35,
        institution: "Maharaja Institute of Technology, Mysore",
        degree: "Bachelors of Engineering (CSE - AI & ML)",
        duration: "2023 - 2027",
        score: "CGPA: 9.11",
        order: 1,
    },
    {
        id: 36,
        institution: "Marimallappa College",
        degree: "PUC",
        duration: "2021 - 2023",
        score: "94.6%",
        order: 2,
    },
    {
        id: 37,
        institution: "Good Shepherd Convent High School",
        degree: "SSLC",
        duration: "2021",
        score: "98.08%",
        order: 3,
    }
];
